name: CI
on:
  pull_request: {}
  push:
    branches: [level-2]
jobs:
  main:
    name: Build, Validate and Deploy
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: w3c/spec-prod@v2
        with:
          W3C_ECHIDNA_TOKEN: ${{ secrets.W3C_TR_TOKEN_L2 }}
          W3C_WG_DECISION_URL: https://docs.google.com/document/d/12AAIbnkt_AH1YjZwUwxirX_7WA7aWOSXpDweCgfqIiQ/edit#heading=h.jc5tpbau2p7z
          W3C_BUILD_OVERRIDE: |
             shortName: trace-context
             specStatus: CRD
